## NumPy

NumPy, abreviatura de Numerical Python, es una potente librería para trabajar con arrays. NumPy es la base de otras bibliotecas de Python como Pandas, Matplotlib, Scikit-learn y Scipy.

NumPy es una alternativa a las listas de Python porque supera las ejecuciones más lentas utilizando el objeto array multidimensional para realizar operaciones lógicas y matemáticas complejas. Esto significa que es más rápido que las listas de Python a la hora de realizar operaciones complejas.

### NumPy Arrays

El ndarray de NumPy es un objeto array N-dimensional que almacena un grupo de tipos de datos similares. Por defecto, cada elemento del ndarray es un objeto de tipo de datos object(dtype).

La función array() acepta una serie de parámetros:
<ol>
    <li> object: Especifica el objeto lista, tupla, diccionario
    <li> dtype: Es opcional utilizado cuando es necesario un type casting.
    <li> order: Especifica la disposición de la matriz
    <li> copy: Si se establece a true el objeto es copiado.
    <li> ndmin: Especifica el número de dimensiones por las que se compondrá el array.
    <li> subok: Si se establece a true, el tipo del array podrá ser cualquier clase.
</ol>

In [1]:
import numpy as np

p_list = np.array([900, 200, 300, 99, 54, 80])
print("This is a list into numpy array:\n", p_list)
print("Type: ", type(p_list))

p_tuple = np.array((50, 60, 90, 105, 90.6, 30.8))
print("This is a tuple into numpy array:\n", p_tuple)
print("Type: ", type(p_tuple))

This is a list into numpy array:
 [900 200 300  99  54  80]
Type:  <class 'numpy.ndarray'>
This is a tuple into numpy array:
 [ 50.   60.   90.  105.   90.6  30.8]
Type:  <class 'numpy.ndarray'>


#### Dimensiones de un array
Las dimensiones pueden ser las siguientes:
- Zero-Dimensional (0-D): Son valores en el array
- One-Dimensional (1-D): Son dimensiones básicas que contienen los arrays D-0
- Two-Dimensional (2-D): Son arrays con arrays 1-D como elementos
- Three-Dimensional (3-D): Son arrays 2-D o matrices

In [2]:
# 0-D
zerod_arr = np.array(30)
print(zerod_arr)
print("Dimension: ", zerod_arr.ndim)

# 1-D
oned_arr = np.array([30, 40, 60, 80, 10])
print(oned_arr)
print("Dimesion: ", oned_arr.ndim)

# 2-D
twod_arr = np.array([[20, 50, 60, 12], [10, 15, 24, 23]])
print(twod_arr)
print("Dimensions: ", twod_arr.ndim)

# 3-D
threed_arr = np.array([twod_arr])
print(threed_arr)
'''
[[[20 50 60 12]
  [10 15 24 23]]]
'''
# or create one
threed_arr2 = np.array([
           [[1,2,3],[4,5,6],[7,8,9]],
           [[9,8,7],[6,5,4],[3,2,1]],
           [[1,2,3],[6,5,6],[7,8,9]]
           ])
print(threed_arr2)
print("Dimension: ", threed_arr.ndim, "&", threed_arr2.ndim)

#create an array of 6 dimensions
sixd_arr = np.array([1, 2, 3, 4], ndmin=6)
print(sixd_arr)
print("Dimensions :", sixd_arr.ndim)

30
Dimension:  0
[30 40 60 80 10]
Dimesion:  1
[[20 50 60 12]
 [10 15 24 23]]
Dimensions:  2
[[[20 50 60 12]
  [10 15 24 23]]]
[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[9 8 7]
  [6 5 4]
  [3 2 1]]

 [[1 2 3]
  [6 5 6]
  [7 8 9]]]
Dimension:  3 & 3
[[[[[[1 2 3 4]]]]]]
Dimensions : 6


#### Creación de arrays
Una de las formas la descrita antes, convertiendo listas, tuplas con el coamndo np.array.

Existe otra forma con el comando np.linspace ,esté comando tiene 3 entradas (start, end, step)

La función np.arange() nos permite crear una serie de valores.

También disponemos de las funciones np.zero, np.ones, np.empty

In [4]:
linspace_arr = np.linspace(2., 5., 6)
print(linspace_arr)

arange_arr = np.arange(1, 30., 4)
print(arange_arr)

zeros_arr = np.zeros((2, 3, 3))
print(zeros_arr)

[2.  2.6 3.2 3.8 4.4 5. ]
[ 1.  5.  9. 13. 17. 21. 25. 29.]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


#### NumPy Data types

Los elementos del array NumPy son NumPy dtypes, donde cada objeto de tipo de datos tiene un bloque de memoria fijo relativo al array.

In [5]:
int_dt = np.dtype(np.int32)
print(int_dt, "\n Type: ", int_dt.type)

complex_dt = np.dtype(np.complex128)
print(complex_dt, "\n Type: ", complex_dt.type)

bool_dt = np.dtype(np.bool_)
print(bool_dt, "\n Type: ", bool_dt.type)

float_dt = np.dtype(np.float32)
print(float_dt, "\n Type: ", float_dt.type)

unsignedInt_dt = np.dtype(np.uint64)
print(unsignedInt_dt, "\n Type: ", unsignedInt_dt.type)

# Character codes
int_dt = np.dtype('i4')
print(int_dt, "\n Type: ", int_dt.type)

float_dt = np.dtype('f8')
print(float_dt, "\n Type: ", float_dt.type)

complex_dt = np.dtype('c16')
print(complex_dt, "\n Type: ", complex_dt.type)

unsignedInt_dt = np.dtype('u8')
print(unsignedInt_dt, "\n Type: ", unsignedInt_dt.type)

int32 
 Type:  <class 'numpy.int32'>
complex128 
 Type:  <class 'numpy.complex128'>
bool 
 Type:  <class 'numpy.bool_'>
float32 
 Type:  <class 'numpy.float32'>
uint64 
 Type:  <class 'numpy.uint64'>
int32 
 Type:  <class 'numpy.int32'>
float64 
 Type:  <class 'numpy.float64'>
complex128 
 Type:  <class 'numpy.complex128'>
uint64 
 Type:  <class 'numpy.uint64'>
